BaseUrl= "http://tzubertowski.github.io/"
LanguageCode= "en-GB"
Title= "devlags | Tomasz Zubertowski"
Paginate = 5 
DefaultContentLanguage = "en"
DisqusShortname = "devlags"
Copyright = "Copyright up to you"
canonifyurls = true
theme = "gohugo-theme-ananke"
themesDir = "themes"

[params]
	description = "passionate developer with no lags"
	cover = "images/header_image.jpg"
	author = "Tomasz Zubertowski"
	authorlocation = "London, United Kingdom"
	authorwebsite = "http://tzubertowski.github.io"
	bio= "backend dev, devops, PHP passionate"
	logo = "images/oo_myface.png"
	googleAnalyticsUserID = "UA-76483272-12"
	# Optional RSS-Link, if not provided it defaults to the standard index.xml
	# RSSLink = "http://feeds.feedburner.com/..."
	githubName = "tzubertowski"
	twitterName = "tzubertowski"
	# facebookName = ""
	linkedinName = "tzubertowski"
	# set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
	hideHUGOSupport = false
  twitter = "https://twitter.com/tzubertowski"
  instagram = ""
  youtube = ""
  github = "https://github.com/tzubertowski"
  linkedin = "http://linkedin.com/in/tzubertowski"
  background_color_class = "bg-black"
  featured_image = "/images/header_image.jpg"
  recent_posts_number = 3

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
	tag = "tags"
	category = "categories"

[[menu.main]]
  name = "About devlags"
  weight = -110
  identifier = "about"
  url = "/post/welcome-party"

[[menu.main]]
  name = "Blog posts"
  weight = -110
  identifier = "post_list"
  url = "/post"

[[menu.main]]
  name = "Feuilletons"
  weight = -110
  identifier = "feuilleton_list"
  url = "/categories/feuilleton/"

