#!/bin/bash

echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"
rm -rf public
mkdir public
git clone git@github.com:tzubertowski/tzubertowski.github.io.git --branch master public

# Build the project.
hugo # if using a theme, replace by `hugo -t <yourtheme>`

# Go To Public folder
cd public

# Commit changes.
msg="rebuilding site `date`"
if [ $# -eq 1 ]
  then msg="$1"
fi
git add --all && git commit -m "$msg"
git push origin master -f

# Push source
cd ../
git add -A .
git commit -m "$msg"
git push origin source

